# Generated by Django 2.2 on 2020-04-08 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0002_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopitaux', to='sprint1.Wilaya'),
        ),
    ]
