# Generated by Django 2.2 on 2020-04-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0006_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='wilaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint1.Wilaya'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint1.Hopital'),
        ),
    ]
