# Generated by Django 2.2 on 2020-04-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0007_auto_20200411_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
