# Generated by Django 2.2 on 2020-04-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0008_auto_20200412_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_doctor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_receptionist',
        ),
    ]
