# Generated by Django 2.2 on 2020-04-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0009_auto_20200412_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='wilaya',
        ),
    ]
