# Generated by Django 2.2 on 2020-04-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0010_remove_doctor_wilaya'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hopital',
            options={'verbose_name_plural': 'Hopitaux'},
        ),
    ]
