# Generated by Django 2.2 on 2020-04-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint2', '0002_auto_20200418_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irm_pic', models.ImageField(default='default.jpg', upload_to='irm_pics')),
                ('irm_categorie', models.CharField(blank=True, choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3')], max_length=2, null=True)),
                ('irm_date', models.DateField(blank=True, null=True)),
                ('id_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sprint2.Patient')),
            ],
        ),
    ]
