# Generated by Django 2.2 on 2020-04-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint2', '0003_irm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irm',
            name='id_patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint2.Patient'),
        ),
    ]
